<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShipmentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        

        $shipments = [
            [
                'tracking_number' => 'TN123456789',
                'status' => 'pending',
                'weight' => 5.5,
                'notes' => 'First shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '123 Main St, City A',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '456 Elm St, City B',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN987654321',
                'status' => 'in_transit',
                'weight' => 10.0,
                'notes' => 'Second shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '789 Oak St, City C',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '321 Pine St, City D',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN112233445',
                'status' => 'delivered',
                'weight' => 7.2,
                'notes' => 'Third shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '101 Maple St, City E',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '202 Birch St, City F',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN556677889',
                'status' => 'pending',
                'weight' => 3.8,
                'notes' => 'Fourth shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '303 Cedar St, City G',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '404 Walnut St, City H',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN998877665',
                'status' => 'in_transit',
                'weight' => 12.5,
                'notes' => 'Fifth shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '505 Spruce St, City I',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '606 Fir St, City J',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN334455667',
                'status' => 'delivered',
                'weight' => 6.0,
                'notes' => 'Sixth shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '707 Ash St, City K',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '808 Beech St, City L',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN778899001',
                'status' => 'pending',
                'weight' => 4.5,
                'notes' => 'Seventh shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '909 Cedar St, City M',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '1010 Elm St, City N',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN223344556',
                'status' => 'in_transit',
                'weight' => 8.7,
                'notes' => 'Eighth shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '1111 Oak St, City O',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '1212 Pine St, City P',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN667788990',
                'status' => 'delivered',
                'weight' => 9.3,
                'notes' => 'Ninth shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '1313 Maple St, City Q',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '1414 Birch St, City R',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tracking_number' => 'TN445566778',
                'status' => 'pending',
                'weight' => 2.0,
                'notes' => 'Tenth shipment',
                'from_country_id' => 1,
                'from_city_id' => 1,
                'from_address' => '1515 Cedar St, City S',
                'to_country_id' => 1,
                'to_city_id' => 1,
                'to_address' => '1616 Walnut St, City T',
                'driver_id' => 1,
                'sender_id' => 1,
                'receiver_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('shipments')->insert($shipments);


    }
}








// use Illuminate\Database\Seeder;
// use Illuminate\Support\Facades\DB;

// class ShipmentsTableSeeder extends Seeder
// {
//     public function run()
//     {
//         $shipments = [
//             [
//                 'tracking_number' => 'TN123456789',
//                 'status' => 'pending',
//                 'weight' => 5.5,
//                 'notes' => 'First shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '123 Main St, City A',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '456 Elm St, City B',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN987654321',
//                 'status' => 'in_transit',
//                 'weight' => 10.0,
//                 'notes' => 'Second shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '789 Oak St, City C',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '321 Pine St, City D',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN112233445',
//                 'status' => 'delivered',
//                 'weight' => 7.2,
//                 'notes' => 'Third shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '101 Maple St, City E',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '202 Birch St, City F',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN556677889',
//                 'status' => 'pending',
//                 'weight' => 3.8,
//                 'notes' => 'Fourth shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '303 Cedar St, City G',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '404 Walnut St, City H',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN998877665',
//                 'status' => 'in_transit',
//                 'weight' => 12.5,
//                 'notes' => 'Fifth shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '505 Spruce St, City I',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '606 Fir St, City J',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN334455667',
//                 'status' => 'delivered',
//                 'weight' => 6.0,
//                 'notes' => 'Sixth shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '707 Ash St, City K',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '808 Beech St, City L',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN778899001',
//                 'status' => 'pending',
//                 'weight' => 4.5,
//                 'notes' => 'Seventh shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '909 Cedar St, City M',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '1010 Elm St, City N',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN223344556',
//                 'status' => 'in_transit',
//                 'weight' => 8.7,
//                 'notes' => 'Eighth shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '1111 Oak St, City O',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '1212 Pine St, City P',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN667788990',
//                 'status' => 'delivered',
//                 'weight' => 9.3,
//                 'notes' => 'Ninth shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '1313 Maple St, City Q',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '1414 Birch St, City R',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'tracking_number' => 'TN445566778',
//                 'status' => 'pending',
//                 'weight' => 2.0,
//                 'notes' => 'Tenth shipment',
//                 'from_country_id' => 1,
//                 'from_city_id' => 1,
//                 'from_address' => '1515 Cedar St, City S',
//                 'to_country_id' => 1,
//                 'to_city_id' => 1,
//                 'to_address' => '1616 Walnut St, City T',
//                 'driver_id' => 1,
//                 'sender_id' => 1,
//                 'receiver_id' => 1,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//         ];

//         DB::table('shipments')->insert($shipments);
//     }
// }